---
title: "Task 19 Karis Saplys"
author: "Karis Saplys"
date: "2022-11-18"
output: 
  html_document:
    theme: cosmo
    keep_md: TRUE
    code_folding: 'hide'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(downloader)
library(tidyverse)
library(USAboundaries)
library(USAboundariesData)
library(ggsflabel)
library(remotes)
library(devtools)
library(ggplot2)
library(maps)
library(leaflet)
```

```{r}
statesmap <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))
```

```{r}
cities <- us_cities() 

states <- us_states()

county <- us_counties()

idahocounties <- us_counties(states = "ID")
```

```{r}
filteredcities <- cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii')
```

```{r}
top3cities <- filteredcities %>%
  group_by(state_name) %>%
  arrange(desc(population))
head(top3cities)

threelargestcities <- top3cities %>%
  slice(1:3)
head(threelargestcities)
```

```{r}
largest <- threelargestcities %>%
  slice(1:1)

middle <- threelargestcities %>%
  slice(2:2)

smallest <- threelargestcities %>%
  slice(3:3)

largestcity <- largest %>%
  select(city)
```


```{r vizz}
plot1 <- leaflet() %>% 
  addTiles() %>%
  addPolygons(data = statesmap, fillColor = 'white', weight = 1, color = 'grey') %>%
  addPolygons(data = idahocounties, fillColor = 'white', , weight = 1, color = 'grey') %>%
  addCircleMarkers(data = smallest, radius = 1, color = 'lightblue', opacity = 1) %>%
  addCircleMarkers(data = middle, radius = 2, color = 'blue', opacity = 1) %>%
  addCircleMarkers(data = largest, radius = 5, color = 'navy', opacity = 1) %>%
  addCircleMarkers(data = largestcity, label = ~city)
  
  
plot1
```