---
title: "Task 12 Karis Saplys"
author: "Karis Saplys"
date: "2022-10-06"
output: 
  html_document:
    theme: cosmo
    keep_md: TRUE
    code_folding: 'hide'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading in the packages}

library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
library(lubridate)
library(ggplot2)
library(grid)
library(corrplot)
library(readr) 
library(haven)
library(readxl)

```

```{r reading in the data}

dat_1 <- tempfile()
download.file("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS", dat_1, mode = "wb")
dat1 <- readRDS(dat_1)
head(dat1)

dat_2 <- tempfile()
download.file("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.csv", dat_2, mode = "wb")
dat2 <- read_csv(dat_2)
head(dat2)

dat_3 <- tempfile()
download.file("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.dta", dat_3, mode = "wb")
dat3 <- read_dta(dat_3)
head(dat3)

dat_4 <- tempfile()
download.file("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.sav", dat_4, mode = "wb")
dat4 <- read_sav(dat_4)
head(dat4)

dat_5 <- tempfile()
download.file("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.xlsx", dat_5, mode = "wb")
dat5 <- read_xlsx(dat_5)
head(dat5)

all_equal(dat1, dat2, dat3, convert = TRUE)
```

```{r main_graphics}

boxplot1 <- ggplot(data=dat1, aes(x=variable, y=value, fill=variable)) +
           geom_boxplot()
boxplot1

jitter1 <- ggplot(data=dat1, aes(x=variable, y=value, fill=variable)) +
           geom_jitter()
jitter1

avgreturn <- ggplot(data=dat1, aes(x=contest_period, y=value, group=variable, color=variable)) +
                  geom_line() +
                  facet_wrap(~variable)
avgreturn
```

Included are a boxplot, jittered plot, and geom_line plot of average returns across the DARTS, DJIA, and PROS data.

```{r tidying}

dat1_tidy <- dat1 %>%
             filter(variable == 'DJIA') %>%
      mutate(contest_period = str_replace_all(contest_period, '19', '_19'),
             contest_period = str_replace(contest_period, 'Febuary', 'February'),
             contest_period = str_replace(contest_period, 'Dec._1993', 'December_1993')) %>%
      separate(contest_period, into = c('Month', 'Year_End'), sep = '-') %>%
      separate(Year_End, into = c('Month', 'Year'), sep = '_') %>%
      arrange(factor(Month, levels = month.name))

head(dat1_tidy, n=10)


saveRDS(dat1_tidy, file='dat1_tidy.rds')
```

```{r 6_month_returns_by_year}

returns <- ggplot(data=dat1_tidy, aes(x=Year, y=value, group=Month, color=variable)) +
                  geom_line() +
                  geom_point() +
                  facet_wrap(~Month)
returns
```

Faceted graphs of Dow Jones Industrial Average returns by month in each year. Downturns in years such as 1998 are very evident, as are bull market runs in years like 1995.

```{r final table from task description}

final_table <- dat1%>%
  filter(variable == "DJIA") %>%
  mutate(contest_period = str_replace_all(contest_period, "19", "_19"),
         contest_period = str_replace(contest_period, "Febuary", "February"),
         contest_period = str_replace(contest_period, "Dec._1993", "December_1993")) %>%
  separate(contest_period, into = c("Month", "Year_end"), sep = "-") %>%
  separate(Year_end, into = c("Month", "Year"), sep = "_") %>%
  pivot_wider(names_from = "Year", values_from = "value") %>%
  arrange(factor(Month, levels = month.name)) %>%
  select(-variable)

head(final_table)
tail(final_table)

```

