---
title: "Task 6 Karis Saplys"
author: "Karis Saplys"
date: "2022-09-13"
output: 
  html_document:
    theme: cosmo
    keep_md: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages}
#install.packages('lubridate')
library(lubridate)
library(readr)
library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
```

```{r iris data}
irisdat <- iris
head(irisdat)
```

```{r iris plot}
best_pwidth <- iris %>%
  group_by(Species) %>%
  filter(row_number(desc(Petal.Width)) == 1)

best_plength <- iris %>%
  group_by(Species) %>%
  filter(row_number(desc(Petal.Length)) == 1)

ggplot(data = iris, mapping = aes(y = Sepal.Width, 
                                  x = Sepal.Length, 
                                  color = Species,
                                  shape = Species)) +
  geom_point() +
  geom_point(size = 3, shape = 1, color = "black", data = best_pwidth) +
  geom_point(size = 3, shape = 1, color = "black", data = best_plength) +
  geom_text(aes(color = Species, label = "Largest Petal Width"), data = best_pwidth, nudge_y = -0.15) +
  geom_text(aes(color = Species, label = "Largest Petal Length"), data = best_plength,nudge_y = -0.15) +
  labs(y = "Sepal Width (cm)",
       x = "Sepal Length (cm)",
       title = "Different Iris Species Have Different Sepal Sizes",
       subtitle = "The Largest Petal Sizes For Each Species Do Not Correspond To The Largest Sepal Sizes") +
  theme(legend.position = "bottom")
```

```{r setting up scrabble plot data}
ScrabbleData <- tempfile()
download.file("https://media.githubusercontent.com/media/fivethirtyeight/data/master/scrabble-games/scrabble_games.csv",
ScrabbleData, mode = "wb")
ScrabbleDat <- read_csv(ScrabbleData)


ScrabbleAll <- ScrabbleDat %>%
  select(date, winnerscore, loserscore) %>%
  pivot_longer(c("winnerscore","loserscore"), names_to = "win-loss", values_to = "score") %>%
  filter(score > 0) %>%
  mutate(year = year(date),
         week = week(date)
  )

```

```{r scrabble plot}
avg_scrabble <- ScrabbleAll %>%
group_by(year, week) %>%
summarise(avglength = mean(score), Date = min(date))
head(avg_scrabble)


after_avg <- ScrabbleAll %>% 
group_by(year, week) %>%
filter(date > as.Date("2006-03-01")) %>%
summarise(avglength = mean (score), Date = min(date))


before_avg <- ScrabbleAll %>% 
group_by(year, week) %>%
filter(date <= as.Date("2006-03-01")) %>%
summarise(avglength = mean (score), Date = min(date))


ggplot(data = avg_scrabble, mapping = aes(x = Date, y = avglength)) +
  geom_point() +
  geom_smooth(data = before_avg, method = 'lm', color="orange") +
  annotate("text", x=as.Date("2005-12-01"), y = 380, label = "Trend Before", color = "orange", size = 3) + geom_smooth(data = after_avg, method = 'lm', color = "blue") +
  annotate("text", x=as.Date("2006-07-15"), y = 380, label = "Trend After", color = "blue", size = 3) + 
  geom_vline(xintercept=as.Date("2006-03-01"), linetype = "dotted") +
  annotate ("text", x = as.Date("2006-03-01"), y = 390, label = "Dictionary\nUpdated", size = 3) +
  labs(y = "Average Score", x = "", title = "Scrabble scores in the age of 'QI' and 'ZA'", subtitle = 'Weekly average scores before and after the addition of around 11,000 words to the Scrabble dictionary', caption = 'Source: FiveThirtyEight') +
  coord_cartesian(ylim = c(355,405), expand = FALSE) +
  scale_x_date(date_breaks = "3 month", 
  limits = as.Date(c('1/6/2005', '1/9/2006'), format = "%d/%m/%Y"), 
  date_labels = "%b-%y" ) + 
  theme_bw()
   
```





