---
title: "Task 18 Karis Saplys"
author: "Karis Saplys"
date: "2022-11-08"
output: 
  html_document:
    theme: cosmo
    keep_md: TRUE
    code_folding: 'hide'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(USAboundaries)
library(USAboundariesData)
library(ggsflabel)
library(remotes)
library(devtools)
library(ggplot2)
library(maps)
```

```{r}
cities <- us_cities() 
  
states <- us_states()

county <- us_counties()

idahocounties <- us_counties(states = "ID")

statesmap <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(statesmap)

no_alaskahawaii <- cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii')
```

```{r}
top3pop <- no_alaskahawaii %>%
  group_by(state_name) %>%
  arrange(desc(population))
head(top3pop)

biggest_cities <- top3pop %>%
  slice(1:3)
head(biggest_cities)

biggest <- biggest_cities %>%
  slice(1:1)
middle <- biggest_cities %>%
  slice(2:2)
smallest <- biggest_cities %>%
  slice(3:3)
```

```{r my_viz}
ggplot() +
  geom_sf(data = statesmap, fill = NA) +
  geom_sf(data = idahocounties, fill = NA) +
  geom_sf(data = smallest, aes(size = population/1000), color = "lightblue") +
  geom_sf(data = middle, aes(size = population/1000), color = "royalblue1") +
  geom_sf(data = biggest, aes(size = population/1000), color = "royalblue4") +
  geom_sf_label(data = biggest, aes(label = city), color = "darkblue", nudge_x = 1.5, nudge_y = 1, size = 2) +
  scale_size_continuous(name = 'Population\n(1,000)') +
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank())
```
