---
title: "Task 10 Karis Saplys"
author: "Karis Saplys"
date: "2022-09-29"
output: 
  html_document:
    theme: cosmo
    keep_md: TRUE
    code_folding: 'hide'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages}
library(lubridate)
library(readr)
library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
```

```{r installing new package and loading data}
#install.packages("devtools") 
library(devtools)

devtools::install_github("drsimonj/ourworldindata")

library(ourworldindata)

head(financing_healthcare)
?financing_healthcare
str(financing_healthcare)

```

```{r  Create a graphic that you could use in a final presentation to summarize world child mortality}

financing_healthcare2 <- financing_healthcare %>%
  group_by(year) %>%
  filter(year > 1800) %>%
  summarise(avg_cm = mean(child_mort, na.rm = TRUE))

head(financing_healthcare2)

cmplot <- ggplot(data=financing_healthcare2, mapping=aes(x=year, y=avg_cm, color="red")) +
  geom_path(size = 1.9) +
  labs(y = "Child Mortality Rate",
       x = "Year",
       title = "World Average Child Mortality Rate of Over Time") +
  theme(legend.position = "none")

cmplot
```

